import type { Metadata } from "next";
import { Parkinsans, Bungee_Inline } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/Sidebar";

const parkinsans = Parkinsans({
  subsets: ["latin"],
  variable: "--font-parkinsans",
  weight: ["300", "400", "500", "600", "700"],
});

const bungeeInline = Bungee_Inline({
  subsets: ["latin"],
  variable: "--font-bungeeinline",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
        className={`${parkinsans.variable} ${bungeeInline.variable} antialiased bg-black text-white font-parkinsans`}
      >
        <Sidebar />
        {/* 
            The ml-[70px] or ml-[85px] ensures the page content 
            doesn't go under the sidebar on desktop 
        */}
        <main className="md:ml-[85px] transition-all duration-300 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
