import type { Metadata } from "next";
import { Parkinsans, Bungee_Inline, Alexandria, Azeret_Mono, Neuton, JetBrains_Mono, Unbounded,  } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/Sidebar";
import ProgressProviders from "@/providers/ProgressProviders";
import SmoothScrollProvider from "@/providers/SmoothScrollProvider";
import InitialLoader from "@/Components/InitialLoader";

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-unbounded",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});


const neuton = Neuton({
  subsets: ["latin"],
  variable: "--font-neuton",
  weight: ["200", "300", "400", "700", "800"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrainsmono",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});


const azeretMono = Azeret_Mono({
  subsets: ["latin"],
  variable: "--font-azeretmono",
  weight: ["200", "300", "400", "500", "600", "700"],
});

const alexandria = Alexandria({
  subsets: ["latin"],
  variable: "--font-alexandria",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const parkinsans = Parkinsans({
  subsets: ["latin"],
  variable: "--font-parkinsans",
  weight: ["300", "400", "500", "600", "700"],
});

const bungeeInline = Bungee_Inline({
  subsets: ["latin"],
  variable: "--font-bungeeinline",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
  className={`${parkinsans.variable} ${bungeeInline.variable} ${azeretMono.variable} ${alexandria.variable} ${jetbrainsMono.variable} ${neuton.variable} ${unbounded.variable} antialiased bg-black text-white`}
>
        {/* Initial Loading Screen */}
        <InitialLoader />

        <ProgressProviders>
        <Sidebar />
        {/*
            The ml-[70px] or ml-[85px] ensures the page content
            doesn't go under the sidebar on desktop
        */}
        <main className="md:ml-[80px] xl:ml-[90px] transition-all duration-300 min-h-screen">
          <SmoothScrollProvider>
          {children}
          </SmoothScrollProvider>
        </main>
        </ProgressProviders>
      </body>
    </html>
  );
}
